# Generated by Django 3.1.5 on 2021-01-26 17:10

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210126_1647'),
    ]

    operations = [
        TrigramExtension()
    ]
