# Generated by Django 3.1.5 on 2021-02-12 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20210126_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='raiting',
            field=models.IntegerField(default=0, verbose_name='Raiting'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replys', related_query_name='reply', to='forum.post', verbose_name='Reply to'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='forum.thread', verbose_name='Thread'),
        ),
        migrations.AlterField(
            model_name='section',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='section',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='raiting',
            field=models.IntegerField(default=0, verbose_name='Raiting'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is closed'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='raiting',
            field=models.IntegerField(default=0, verbose_name='Raiting'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', related_query_name='thread', to='forum.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
