# Generated by Django 3.1.5 on 2021-01-21 17:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.png', force_format='PNG', keep_meta=True, quality=0, size=[250, 250], upload_to='avatars'),
        ),
    ]
